module.exports = {
  POSTBACK_TITLE: {
    ADD_TODO: `Add Todo`,
    LIST_TODO: `List Todos`,
    DELETE_TODO: `Delete`,
    EDIT_TODO: `Edit`,
    SETTINGS: 'Settings',
    SET_DAILY_REMINDER: `Set Reminder`,
    DELETE_DAILY_REMINDER: `Delete Reminder`,
    SET_TIME_ZONE: `Set Timezone`,
  },
  INPUT_TYPE: {
    ADD_TODO: `input/addTodo`,
    EDIT_TODO: `input/editTodo`,
    EDIT_TODO_NOTES: `input/editTodo/notes`,
    EDIT_TODO_DUE_DATE: `input/editTodo/dueDate`,
    EDIT_TODO_REMINDER: `input/editTodo/reminder`,
    SET_DAILY_REMINDER: `input/setDailyReminder`,
    DELETE_DAILY_REMINDER: `input/deleteDailyReminder`,
    SET_TIME_ZONE: `input/setTimezone`,
  },
  SHORT_CUT: {
    ADD_TODO: '/a ',
    LIST_TODO: 'list',
    HELP: `Help`,
  },
  QUICK_REPLY: {
    ADD_TODO: 'quickReply/addTodo',
    VIEW_TODO: 'quickReply/viewTodo',
    DELETE_TODO: 'quickReply/deleteTodo',
    EDIT_TODO: 'quickReply/editTodo',
    NOTHING: 'quickReply/nothing',
    CHOOSE_TODO: 'quickReply/chooseTodo',
  },
  DAY_OF_WEEK: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
};
